#!/usr/bin/env python3
"""
Turn data/timetable.json into src/data/timetable.ts.

The app ships the timetable as a compact TS module rather than fetching JSON:
the whole term is 220 rows and never changes at runtime, so bundling it keeps
the app working offline and removes a loading state from the home screen.

Run after parse_timetable.py:  npm run data
"""
import json
import os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The sheet contains subject CODES only. These expansions are inferred —
# correct them here and re-run; nothing else needs touching.
NAMES = {
    "EHV":   "Ethics & Human Values",
    "FMS":   "Fundamentals of Mathematics",
    "IIS":   "Information & Info Systems",
    "IKS":   "Indian Knowledge Systems",
    "OC-II": "Oral Communication II",
    "PHI-I": "Philosophy I",
    "POE":   "Principles of Economics",
    "PSY":   "Psychology",
    "Y&M-I": "Yoga & Meditation I",
}

with open(os.path.join(ROOT, "data", "timetable.json")) as f:
    payload = json.load(f)
S = payload["sessions"]

dates = sorted({x["date"] for x in S})
times = sorted({x["start"] for x in S})
subs  = sorted({x["subject"] for x in S})
count = Counter((x["subject"], x["group"]) for x in S)

missing = [s for s in subs if s not in NAMES]
if missing:
    raise SystemExit(f"add these subject codes to NAMES in scripts/to_js.py: {missing}")

SUBS = [[s, NAMES[s], count[(s, "B")],
         sorted({y["faculty"] for y in S if y["subject"] == s})[0]] for s in subs]
TIMES = [[t, sorted({y["end"] for y in S if y["start"] == t})[0]] for t in times]
ROWS = ";".join(
    "%d.%d.%d.%d.%d" % (dates.index(x["date"]), times.index(x["start"]),
                        subs.index(x["subject"]), x["n"], 0 if x["group"] == "A" else 1)
    for x in S
)

out = f'''/* GENERATED by scripts/to_js.py — do not edit by hand.
   Source: data/timetable.xlsx -> data/timetable.json -> here.
   Regenerate with: npm run data

   {len(S)} sessions across {len(dates)} teaching days, {dates[0]} to {dates[-1]}.
   This is a FLAT DATED SCHEDULE, not a weekly repeating pattern — there is no
   recurrence rule to expand, and every session is listed individually. */

import type {{ Session, Group }} from "../types.js";

export const DATES: string[] = {json.dumps(dates)};
export const TIMES: [string, string][] = {json.dumps(TIMES)};

/** [code, displayName, totalSessionsPerGroup, faculty] */
export const SUBS: [string, string, number, string][] = {json.dumps(SUBS, ensure_ascii=False)};

/** "dateIdx.timeIdx.subjectIdx.sessionNumber.group" — group 0 = A, 1 = B */
const ROWS = "{ROWS}";

export const TERM: {{ start: string; end: string }} = {{ start: DATES[0], end: DATES[DATES.length - 1] }};

/* Group A sits in CR-06, group B in CR-08, except Yoga which is in CR-02
   for both. Derived rather than stored — it holds for all {len(S)} sessions. */
const roomFor = (code: string, group: Group): string =>
  code === "Y&M-I" ? "CR-02" : group === "A" ? "CR-06" : "CR-08";

export const SESSIONS: Session[] = ROWS.split(";").map((row) => {{
  const [d, t, s, n, g] = row.split(".").map(Number);
  const [code, name, total, faculty] = SUBS[s];
  const group: Group = g === 0 ? "A" : "B";
  return {{
    id: `${{code}}-${{group}}-${{n}}`,
    date: DATES[d], start: TIMES[t][0], end: TIMES[t][1],
    code, name, faculty, total, colorIdx: s, n, group,
    room: roomFor(code, group),
  }};
}});

export const sessionsForGroup = (group: Group): Session[] =>
  SESSIONS.filter((s) => s.group === group);

export const sessionsForSubject = (code: string, group: Group): Session[] =>
  SESSIONS.filter((s) => s.code === code && s.group === group);
'''

dest = os.path.join(ROOT, "src", "data", "timetable.ts")
with open(dest, "w", encoding="utf-8") as f:
    f.write(out)
print(f"wrote {dest} ({len(S)} sessions, {len(subs)} subjects)")
